############################################################
# Panda personal configuration
############################################################

DEFAULT_ENV="torch-py312"

DEFAULT_GPU="5090"

DEFAULT_CPUS=4

DEFAULT_MEM="16G"

CONDA_INIT="$HOME/miniconda3/etc/profile.d/conda.sh"
