ClusterName=pandacluster

SlurmctldHost=shuanshuan

AuthType=auth/munge

SlurmUser=slurm

GresTypes=gpu

ProctrackType=proctrack/linuxproc
TaskPlugin=task/affinity

StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd

SchedulerType=sched/backfill

SelectType=select/cons_tres
SelectTypeParameters=CR_Core

NodeName=shuanshuan CPUs=8  Sockets=1 CoresPerSocket=4  ThreadsPerCore=2 RealMemory=64231  Gres=gpu:2 State=UNKNOWN
NodeName=xinxin     CPUs=32 Sockets=1 CoresPerSocket=16 ThreadsPerCore=2 RealMemory=31973  Gres=gpu:1 State=UNKNOWN
NodeName=tohui      CPUs=32 Sockets=1 CoresPerSocket=16 ThreadsPerCore=2 RealMemory=126424 Gres=gpu:1 State=UNKNOWN

PartitionName=cpu Nodes=ALL Default=YES State=UP

#
# GPU partitions
#

PartitionName=gpu       Nodes=shuanshuan,tohui,xinxin Default=NO State=UP

PartitionName=tohui      Nodes=tohui      Default=NO State=UP
PartitionName=shuanshuan Nodes=shuanshuan Default=NO State=UP
PartitionName=xinxin     Nodes=xinxin     Default=NO State=UP

